### ISSUE TITLE
one of the tests fails

### ISSUE THREAD

**Issue by armantorkzaban** [dartclub/sweepline_intersections#3]
chileKinked.geojson results 0 intersections while the original  library states 2. This could be from a bug from my implementation to an error in the .geojson.
@lukas-h, aside from that, the library is good to be released with warning for the users that it is a WIP.

**Comment by armantorkzaban** [comment]
[Asked the author](https://github.com/rowanwins/sweepline-intersections/issues/15) in regards to this commit https://github.com/rowanwins/sweepline-intersections/commit/f61d0a75b61bb37ae5a5c964408d1c946b242538

**Comment by armantorkzaban** [comment]
Issue was the MultiPolygon case was not covered. Reported to the author as well.

**Comment by lukas-h** [comment]
This is nice 👍 👍 👍
