### ISSUE TITLE
Latitude and Longitude are reversed on return of getIntersection

### ISSUE THREAD

**Issue by MattyBoy4444** [dartclub/sweepline_intersections#8]
The return values are reversed in utils.dart.

**Comment by MattyBoy4444** [comment]
Forget it.  I figured out my problem.  DAMN turf.Position taking Longitude first!!

**Comment by lukas-h** [comment]
Hi, thanks for using the library. The library is still very new, so there might be some issues still.
If you encounter other bugs, please report them 😄 

lat/lng/alt order is defined by the RFC standard for Geojson.
